import assert from "node:assert/strict";
import test from "node:test";

import { sanitizeAiStudioDebugValue, toPublicDocDetail } from "@/lib/ai-studio/public";

test("serializes public model detail without kie urls, anchors, or callback fields", () => {
  const detail = toPublicDocDetail({
    id: "video:generate-ai-video",
    category: "video",
    title: "Runway - Text to Video",
    docUrl: "https://docs.kie.ai/runway-api/generate-ai-video.md",
    provider: "Runway",
    endpoint: "/api/v1/runway/generate",
    method: "POST",
    modelKeys: ["runway-duration-5-generate"],
    requestSchema: {
      type: "object",
      properties: {
        model: {
          type: "string",
          default: "runway-duration-5-generate",
          description: "Generate with Kie AI",
        },
        callBackUrl: {
          type: "string",
        },
        progressCallBackUrl: {
          type: "string",
        },
        waterMark: {
          type: "string",
          example: "kie.ai",
        },
      },
    },
    examplePayload: {
      prompt: "Create a launch trailer for Kie AI",
      model: "runway-duration-5-generate",
      waterMark: "kie.ai",
      callBackUrl: "https://api.example.com/callback",
      progressCallBackUrl: "https://api.example.com/progress",
    },
    pricingRows: [
      {
        modelDescription: "Runway, text-to-video, 5.0s-720p",
        interfaceType: "video",
        provider: "Runway",
        creditPrice: "40",
        creditUnit: "per video",
        usdPrice: "0.2",
        falPrice: "0.5",
        discountRate: 60,
        anchor: "https://kie.ai/runway?model=runway-duration-5-generate",
        discountPrice: false,
      },
    ],
  });

  assert.equal("docUrl" in detail, false);
  assert.equal("callBackUrl" in (detail.requestSchema?.properties ?? {}), false);
  assert.equal("progressCallBackUrl" in (detail.requestSchema?.properties ?? {}), false);
  assert.equal("callBackUrl" in detail.examplePayload, false);
  assert.equal("progressCallBackUrl" in detail.examplePayload, false);
  assert.equal(detail.examplePayload.waterMark, "AI Studio");
  assert.equal(detail.pricingRows[0] && "anchor" in detail.pricingRows[0], false);
  assert.equal(detail.pricingRows[0]?.runtimeModel, "runway-duration-5-generate");
  assert.equal(JSON.stringify(detail).toLowerCase().includes("kie"), false);
});

test("sanitizes debug payloads before returning them to the browser", () => {
  const value = sanitizeAiStudioDebugValue({
    message: "Generated by Kie AI",
    docs: "https://docs.kie.ai/runway-api/generate-ai-video.md",
    nested: {
      brand: "kie.ai",
    },
  });

  assert.equal(JSON.stringify(value).toLowerCase().includes("kie"), false);
});
