import assert from "node:assert/strict";
import test from "node:test";

import {
  getPublicAiStudioModelId,
  sanitizeAiStudioDebugValue,
  toPublicCatalogEntry,
  toPublicDocDetail,
} from "@/lib/ai-studio/public";

test("serializes public model detail without kie urls or callback fields", () => {
  const detail = toPublicDocDetail({
    id: "video:grok-imagine-text-to-video",
    category: "video",
    title: "Grok Imagine Text to Video",
    docUrl: "https://docs.kie.ai/market/grok-imagine/text-to-video.md",
    provider: "Grok Imagine",
    endpoint: "/api/v1/runway/generate",
    method: "POST",
    modelKeys: ["grok-imagine/text-to-video"],
    requestSchema: {
      type: "object",
      properties: {
        model: {
          type: "string",
          default: "grok-imagine/text-to-video",
          description: "Generate with Kie AI",
        },
        callBackUrl: {
          type: "string",
        },
        progressCallBackUrl: {
          type: "string",
        },
        waterMark: {
          type: "string",
          example: "kie.ai",
        },
      },
    },
    examplePayload: {
      prompt: "Create a launch trailer for Kie AI",
      model: "grok-imagine/text-to-video",
      waterMark: "kie.ai",
      callBackUrl: "https://api.example.com/callback",
      progressCallBackUrl: "https://api.example.com/progress",
    },
  });

  assert.equal("docUrl" in detail, false);
  assert.equal("vendor" in detail, false);
  assert.equal("callBackUrl" in (detail.requestSchema?.properties ?? {}), false);
  assert.equal("progressCallBackUrl" in (detail.requestSchema?.properties ?? {}), false);
  assert.equal("callBackUrl" in detail.examplePayload, false);
  assert.equal("progressCallBackUrl" in detail.examplePayload, false);
  assert.equal(detail.examplePayload.waterMark, "AI Studio");
  assert.equal(JSON.stringify(detail).toLowerCase().includes("kie"), false);
  assert.equal(detail.requestMeta.bodyType, "json");
  assert.deepEqual(detail.requestMeta.hiddenFields.sort(), [
    "callBackUrl",
    "progressCallBackUrl",
  ]);
  assert.deepEqual(detail.requestMeta.injectedFields.sort(), [
    "callBackUrl",
    "progressCallBackUrl",
  ]);
  assert.equal(detail.taskMeta.mode, "poll+callback");
  assert.equal(detail.taskMeta.statusEndpoint, "/api/v1/runway/record-detail");
});

test("removes pricing doc urls from public model detail", () => {
  const detail = toPublicDocDetail({
    id: "image:ama-gpt-image-2",
    category: "image",
    title: "GPT Image 2",
    docUrl: "https://docs.apimart.ai/en/api-reference/images/gpt-image-2/generation",
    provider: "GPT Image",
    endpoint: "/api/v1/gpt-image-2/generate",
    method: "POST",
    modelKeys: ["gpt-image-2"],
    requestSchema: null,
    examplePayload: {},
    pricing: {
      docUrl: "https://docs.apimart.ai/en/api-reference/images/gpt-image-2/generation",
      price_txt: "$0.01 per image",
      price_key: "default",
      price_map: {
        default: 10,
      },
    },
  });

  assert.equal("docUrl" in (detail.pricing ?? {}), false);
  assert.equal(detail.pricing?.price_txt, "$0.01 per image");
  assert.deepEqual(detail.pricing?.price_map, { default: 10 });
});

test("hides vendor while preserving alias-based public ids for seedance vip models", () => {
  const detail = toPublicDocDetail({
    id: "video:bytedance-seedance-2",
    category: "video",
    title: "bytedance-seedance-2",
    alias: "seedance-2-0-vip",
    vendor: "kie",
    docUrl: "https://docs.kie.ai/market/bytedance/seedance-2.md",
    provider: "ByteDance",
    endpoint: "/api/v1/jobs/createTask",
    method: "POST",
    modelKeys: ["bytedance/seedance-2"],
    requestSchema: {
      type: "object",
      properties: {
        model: {
          type: "string",
          enum: ["bytedance/seedance-2"],
          default: "bytedance/seedance-2",
          description: "Must be `bytedance/seedance-2`",
          examples: ["bytedance/seedance-2"],
        },
      },
    },
    examplePayload: {
      model: "bytedance/seedance-2",
    },
  });

  assert.equal(detail.id, "video:seedance-2-0-vip");
  assert.deepEqual(detail.modelKeys, ["seedance-2-0-vip"]);
  assert.equal(detail.examplePayload.model, "seedance-2-0-vip");
  assert.equal("vendor" in detail, false);
});

test("sanitizes debug payloads before returning them to the browser", () => {
  const value = sanitizeAiStudioDebugValue({
    message: "Generated by Kie AI",
    docs: "https://docs.kie.ai/runway-api/generate-ai-video.md",
    nested: {
      brand: "kie.ai",
    },
  });

  assert.equal(JSON.stringify(value).toLowerCase().includes("kie"), false);
});

test("replaces provider model names with alias in public detail output", () => {
  const detail = toPublicDocDetail({
    id: "video:sora2-text-to-video-standard",
    category: "video",
    title: "Sdance - Text to Video",
    alias: "sdance-text-to-video",
    docUrl: "https://docs.kie.ai/market/sora2/sora-2-text-to-video.md",
    provider: "Sdance",
    endpoint: "/api/v1/jobs/createTask",
    method: "POST",
    modelKeys: ["sora-2-text-to-video"],
    requestSchema: {
      type: "object",
      properties: {
        model: {
          type: "string",
          enum: ["sora-2-text-to-video"],
          default: "sora-2-text-to-video",
          description: "Must be `sora-2-text-to-video`",
          examples: ["sora-2-text-to-video"],
        },
      },
    },
    examplePayload: {
      model: "sora-2-text-to-video",
    },
  });

  assert.deepEqual(detail.modelKeys, ["sdance-text-to-video"]);
  assert.equal(detail.examplePayload.model, "sdance-text-to-video");
  assert.deepEqual(detail.requestSchema?.properties?.model?.enum, [
    "sdance-text-to-video",
  ]);
  assert.equal(detail.requestSchema?.properties?.model?.default, "sdance-text-to-video");
  assert.equal(detail.id, "video:sdance-text-to-video");
});

test("uses alias-derived public ids when available", () => {
  assert.equal(
    getPublicAiStudioModelId({
      id: "video:sora2-text-to-video-standard",
      category: "video",
      alias: "sdance-text-to-video",
    }),
    "video:sdance-text-to-video",
  );
  assert.equal(
    getPublicAiStudioModelId({
      id: "image:z-image",
      category: "image",
      alias: null,
    }),
    "image:z-image",
  );
});

test("uses alias-derived public ids in catalog entries", () => {
  const entry = toPublicCatalogEntry({
    id: "video:sora2-text-to-video-standard",
    category: "video",
    title: "Sdance - Text to Video",
    alias: "sdance-text-to-video",
    docUrl: "https://docs.kie.ai/market/sora2/sora-2-text-to-video.md",
    provider: "Sdance",
  });

  assert.equal(entry.id, "video:sdance-text-to-video");
  assert.equal("docUrl" in entry, false);
});

test("removes nested callback fields from public detail and exposes matching metadata", () => {
  const detail = toPublicDocDetail({
    id: "video:nested-callback-test",
    category: "video",
    title: "Nested Callback Test",
    docUrl: "https://docs.kie.ai/market/example/nested-callback.md",
    provider: "Example",
    endpoint: "/api/v1/jobs/createTask",
    method: "POST",
    modelKeys: ["example/nested-callback"],
    requestSchema: {
      type: "object",
      properties: {
        input: {
          type: "object",
          properties: {
            prompt: {
              type: "string",
            },
            callbackUrl: {
              type: "string",
            },
          },
        },
        config: {
          type: "object",
          properties: {
            webhook_url: {
              type: "string",
            },
          },
        },
      },
    },
    examplePayload: {
      input: {
        prompt: "hello",
        callbackUrl: "https://example.com/callback",
      },
      config: {
        webhook_url: "https://example.com/webhook",
      },
    },
  });

  assert.equal("callbackUrl" in (detail.requestSchema?.properties?.input?.properties ?? {}), false);
  assert.equal("webhook_url" in (detail.requestSchema?.properties?.config?.properties ?? {}), false);
  assert.equal("callbackUrl" in (detail.examplePayload.input ?? {}), false);
  assert.equal("webhook_url" in (detail.examplePayload.config ?? {}), false);
  assert.deepEqual(detail.requestMeta.hiddenFields.sort(), ["callbackUrl", "webhook_url"]);
  assert.deepEqual(detail.requestMeta.injectedFields.sort(), ["callbackUrl", "webhook_url"]);
  assert.equal(detail.taskMeta.mode, "poll+callback");
});
