/**
 * Pricing Configuration File
 * 定价配置文件
 *
 * This file serves as the single source of truth for pricing plans.
 * AI can edit this file directly, then run `pnpm db:seed` to sync to database.
 *
 * 此文件作为定价计划的单一真相来源。
 * AI 可以直接编辑此文件，然后运行 `pnpm db:seed` 同步到数据库。
 *
 * Usage / 使用方法:
 * 1. Edit this file to add/update/remove pricing plans
 * 2. Run `pnpm db:seed` to sync changes to database
 * 3. Run `pnpm db:export-pricing` to export current database state back to this file
 *
 * Type Safety / 类型安全:
 * Types are derived from database schema (lib/db/schema.ts).
 * If schema changes, TypeScript will catch any mismatches.
 * 类型从数据库 schema 推导，如果 schema 变更，TypeScript 会捕获不匹配的错误。
 *
 * Auto-generated at: 2025-12-30T04:02:42.809Z
 */

import type { InferInsertModel } from 'drizzle-orm'
import { pricingPlanGroups as pricingPlanGroupsTable, pricingPlans as pricingPlansTable } from '../schema'

// ============================================================================
// Type Definitions - Derived from Schema / 类型定义 - 从 Schema 推导
// ============================================================================

/**
 * Pricing Plan Config type derived from database schema.
 * Omit auto-generated fields (createdAt, updatedAt).
 *
 * 从数据库 schema 推导的定价计划配置类型。
 * 排除自动生成的字段（createdAt, updatedAt）。
 */
export type PricingPlanConfig = Omit<
  InferInsertModel<typeof pricingPlansTable>,
  'createdAt' | 'updatedAt'
> & {
  paypalProductId?: string | null
  paypalPlanId?: string | null
}

/**
 * Pricing Group Config type derived from database schema.
 *
 * 从数据库 schema 推导的定价分组配置类型。
 */
export type PricingGroupConfig = Omit<
  InferInsertModel<typeof pricingPlanGroupsTable>,
  'createdAt'
>

// ============================================================================
// Helper Types for JSONB Fields / JSONB 字段的辅助类型
// ============================================================================

/**
 * Feature item structure for the features JSONB field.
 * 功能项结构，用于 features JSONB 字段。
 */
export interface PricingFeature {
  description: string
  included: boolean
  bold?: boolean
  href?: string
}

/**
 * Localized content structure for langJsonb field.
 * 多语言内容结构，用于 langJsonb 字段。
 */
export interface LocalizedPricingContent {
  cardTitle?: string
  cardDescription?: string
  displayPrice?: string
  originalPrice?: string
  priceSuffix?: string
  highlightText?: string
  buttonText?: string
  currency?: string
  features?: PricingFeature[]
}

/**
 * Benefits structure for benefitsJsonb field.
 * 权益结构，用于 benefitsJsonb 字段。
 */
export interface PricingBenefits {
  /** One-time credits granted on purchase / 购买时授予的一次性积分 */
  oneTimeCredits?: number
  /** Monthly credits for subscriptions / 订阅的月度积分 */
  monthlyCredits?: number
  /** Total months for yearly plans / 年度计划的总月数 */
  totalMonths?: number
  /** Custom fields / 自定义字段 */
  [key: string]: unknown
}

// ============================================================================
// Pricing Groups / 定价分组
// ============================================================================

export const pricingGroups: PricingGroupConfig[] = [
  { slug: 'default' },
  { slug: 'monthly' },
  { slug: 'onetime' },
  { slug: 'no-payment' },
  { slug: 'annual' },
]

// ============================================================================
// Pricing Plans / 定价计划
// ============================================================================

const testPricingPlans: PricingPlanConfig[] = [

  // ==========================================================================
  // Annual Plans
  // ==========================================================================
  {
    id: '045ff9a8-63e1-4cee-a583-aa29a562661a',
    environment: 'test',
    groupSlug: 'annual',
    cardTitle: 'Standard',
    cardDescription: 'For individuals just getting started.',
    provider: 'paypal',
    paypalProductId: '',
    paypalPlanId: '',
    stripePriceId: 'TODO_UPDATE_STRIPE_PRICE_ID',
    stripeProductId: 'TODO_UPDATE_STRIPE_PRODUCT_ID',
    creemProductId: '',
    paymentType: 'recurring',
    recurringInterval: 'year',
    price: '118.80',
    currency: 'USD',
    displayPrice: '$9.90',
    priceSuffix: '/mo',
    features: [
      { included: true, description: 'High-fidelity image generation' },
      { included: true, description: 'Precise image editing' },
      { included: true, description: 'Clear text rendering for posters and ads' },
      { included: true, description: 'Stable style consistency across batches' },
      { included: true, description: 'PNG/JPEG export' },
      { included: true, description: 'Commercial Use' },
      { included: true, description: 'Standard Queue' },
      { included: true, description: 'Core workflow tools included' },
    ],
    isHighlighted: false,
    buttonText: 'Get Started',
    displayOrder: 1,
    isActive: true,
    langJsonb: {
      en: {
        cardTitle: 'Standard',
        cardDescription: 'For individuals just getting started.',
        displayPrice: '$9.90',
        priceSuffix: '/mo',
        features: [
          { included: true, description: 'High-fidelity image generation' },
          { included: true, description: 'Precise image editing' },
          { included: true, description: 'Clear text rendering for posters and ads' },
          { included: true, description: 'Stable style consistency across batches' },
          { included: true, description: 'PNG/JPEG export' },
          { included: true, description: 'Commercial Use' },
          { included: true, description: 'Standard Queue' },
          { included: true, description: 'Core workflow tools included' },
        ],
        buttonText: 'Get Started',
      },
      zh: {
        cardTitle: '标准版',
        cardDescription: '适合刚刚起步的个人。',
        displayPrice: '$9.90',
        priceSuffix: '/月',
        features: [
          { included: true, description: '高保真图像生成' },
          { included: true, description: '精细化图像编辑' },
          { included: true, description: '海报与营销文案文字更清晰' },
          { included: true, description: '批量出图风格更稳定' },
          { included: true, description: '支持 PNG/JPEG 导出' },
          { included: true, description: '支持商业用途' },
          { included: true, description: '标准队列' },
          { included: true, description: '包含核心图像工作流能力' },
        ],
        buttonText: 'Get Started',
      },
      ja: {
        cardTitle: 'スタンダード',
        cardDescription: 'これから始める個人向け。',
        displayPrice: '$9.90',
        priceSuffix: '/月',
        features: [
          { included: true, description: '高忠実度の画像生成' },
          { included: true, description: '精密な画像編集' },
          { included: true, description: 'ポスター/広告向けの文字レンダリング' },
          { included: true, description: 'バッチ生成で安定したスタイル一貫性' },
          { included: true, description: 'PNG/JPEG 書き出し' },
          { included: true, description: '商用利用' },
          { included: true, description: '標準キュー' },
          { included: true, description: 'コア画像ワークフロー機能' },
        ],
        buttonText: 'Get Started',
      },
    },
    benefitsJsonb: {
      monthlyCredits: 1600,
      totalMonths: 12,
    },
  },
  {
    id: 'a9fada2f-1051-46b7-af65-e2d8e40c1c32',
    environment: 'test',
    groupSlug: 'annual',
    cardTitle: 'Pro',
    cardDescription: 'For creators who need more power.',
    provider: 'paypal',
    paypalProductId: '',
    stripePriceId: 'TODO_UPDATE_STRIPE_PRICE_ID',
    stripeProductId: 'TODO_UPDATE_STRIPE_PRODUCT_ID',
    creemProductId: '',
    paypalPlanId: '',
    paymentType: 'recurring',
    recurringInterval: 'year',
    price: '358.80',
    currency: 'USD',
    displayPrice: '$29.90',
    priceSuffix: '/mo',
    features: [
      { included: true, description: 'High-fidelity image generation' },
      { included: true, description: 'Advanced image editing and local refinements' },
      { included: true, description: 'Clear text rendering for marketing creatives' },
      { included: true, description: 'Stronger style consistency for batch output' },
      { included: true, description: 'PNG/JPEG export' },
      { included: true, description: 'Commercial Use' },
      { included: true, description: 'Fast Generation Queue' },
      { included: true, description: 'Priority Support' },
    ],
    isHighlighted: true,
    highlightText: 'Most Popular',
    buttonText: 'Get Pro',
    displayOrder: 2,
    isActive: true,
    langJsonb: {
      en: {
        cardTitle: 'Pro',
        cardDescription: 'For creators who need more power.',
        displayPrice: '$29.90',
        priceSuffix: '/mo',
        features: [
          { included: true, description: 'High-fidelity image generation' },
          { included: true, description: 'Advanced image editing and local refinements' },
          { included: true, description: 'Clear text rendering for marketing creatives' },
          { included: true, description: 'Stronger style consistency for batch output' },
          { included: true, description: 'PNG/JPEG export' },
          { included: true, description: 'Commercial Use' },
          { included: true, description: 'Fast Generation Queue' },
          { included: true, description: 'Priority Support' },
        ],
        buttonText: 'Get Pro',
        highlightText: 'Most Popular',
      },
      zh: {
        cardTitle: '专业版',
        cardDescription: '适合需要更多功能的创作者。',
        displayPrice: '$29.90',
        priceSuffix: '/月',
        features: [
          { included: true, description: '高保真图像生成' },
          { included: true, description: '高级图像编辑与局部重绘' },
          { included: true, description: '营销素材文字渲染更清晰' },
          { included: true, description: '批量生产风格一致性更强' },
          { included: true, description: '支持 PNG/JPEG 导出' },
          { included: true, description: '支持商业用途' },
          { included: true, description: '快速生成队列' },
          { included: true, description: '优先支持' },
        ],
        buttonText: 'Get Pro',
        highlightText: '最受欢迎',
      },
      ja: {
        cardTitle: 'プロ',
        cardDescription: 'より多くの機能を必要とするクリエイター向け。',
        displayPrice: '$29.90',
        priceSuffix: '/月',
        features: [
          { included: true, description: '高忠実度の画像生成' },
          { included: true, description: '高度な画像編集と部分修正' },
          { included: true, description: 'マーケ素材向けの文字レンダリング' },
          { included: true, description: 'バッチ出力でより強いスタイル一貫性' },
          { included: true, description: 'PNG/JPEG 書き出し' },
          { included: true, description: '商用利用' },
          { included: true, description: '高速生成キュー' },
          { included: true, description: '優先サポート' },
        ],
        buttonText: 'Get Pro',
        highlightText: '一番人気',
      },
    },
    benefitsJsonb: {
      monthlyCredits: 5400,
      totalMonths: 12,
    },
  },
  {
    id: '5fb22f30-cb8c-4eaf-9242-d33ab01e3c21',
    environment: 'test',
    groupSlug: 'annual',
    cardTitle: 'Max',
    cardDescription: 'For studios and professionals.',
    provider: 'paypal',
    paypalProductId: '',
    paypalPlanId: '',
    stripePriceId: 'TODO_UPDATE_STRIPE_PRICE_ID',
    stripeProductId: 'TODO_UPDATE_STRIPE_PRODUCT_ID',
    creemProductId: '',
    paymentType: 'recurring',
    recurringInterval: 'year',
    price: '958.80',
    currency: 'USD',
    displayPrice: '$79.90',
    priceSuffix: '/mo',
    features: [
      { included: true, description: 'High-fidelity image generation' },
      { included: true, description: 'Advanced image editing and local refinements' },
      { included: true, description: 'Clear text rendering for complex layouts' },
      { included: true, description: 'Best style consistency for large batches' },
      { included: true, description: 'PNG/JPEG export' },
      { included: true, description: 'Commercial Use' },
      { included: true, description: 'Instant Queue' },
      { included: true, description: 'API Access' },
    ],
    isHighlighted: false,
    buttonText: 'Get Max',
    displayOrder: 3,
    isActive: true,
    langJsonb: {
      en: {
        cardTitle: 'Max',
        cardDescription: 'For studios and professionals.',
        displayPrice: '$79.90',
        priceSuffix: '/mo',
        features: [
          { included: true, description: 'High-fidelity image generation' },
          { included: true, description: 'Advanced image editing and local refinements' },
          { included: true, description: 'Clear text rendering for complex layouts' },
          { included: true, description: 'Best style consistency for large batches' },
          { included: true, description: 'PNG/JPEG export' },
          { included: true, description: 'Commercial Use' },
          { included: true, description: 'Instant Queue' },
          { included: true, description: 'API Access' },
        ],
        buttonText: 'Get Max',
      },
      zh: {
        cardTitle: '终极版',
        cardDescription: '适合工作室和专业人士。',
        displayPrice: '$79.90',
        priceSuffix: '/月',
        features: [
          { included: true, description: '高保真图像生成' },
          { included: true, description: '高级图像编辑与局部重绘' },
          { included: true, description: '复杂排版文字渲染更稳定' },
          { included: true, description: '大规模批量出图风格一致性最佳' },
          { included: true, description: '支持 PNG/JPEG 导出' },
          { included: true, description: '支持商业用途' },
          { included: true, description: '即时队列' },
          { included: true, description: 'API 访问' },
        ],
        buttonText: 'Get Max',
      },
      ja: {
        cardTitle: 'マックス',
        cardDescription: 'スタジオや専門家向け。',
        displayPrice: '$79.90',
        priceSuffix: '/月',
        features: [
          { included: true, description: '高忠実度の画像生成' },
          { included: true, description: '高度な画像編集と部分修正' },
          { included: true, description: '複雑なレイアウトでも安定した文字レンダリング' },
          { included: true, description: '大規模バッチで最高のスタイル一貫性' },
          { included: true, description: 'PNG/JPEG 書き出し' },
          { included: true, description: '商用利用' },
          { included: true, description: '即時キュー' },
          { included: true, description: 'API アクセス' },
        ],
        buttonText: 'Get Max',
      },
    },
    benefitsJsonb: {
      monthlyCredits: 16000,
      totalMonths: 12,
    },
  },

  // ==========================================================================
  // Monthly Plans
  // ==========================================================================
  {
    id: '1a92a88c-203a-4b4c-8468-54b8761a9037',
    environment: 'test',
    groupSlug: 'monthly',
    cardTitle: 'Standard',
    cardDescription: 'For individuals just getting started.',
    provider: 'paypal',
    paypalProductId: '',
    paypalPlanId: '',
    stripePriceId: 'TODO_UPDATE_STRIPE_PRICE_ID',
    stripeProductId: 'TODO_UPDATE_STRIPE_PRODUCT_ID',
    creemProductId: '',
    paymentType: 'recurring',
    recurringInterval: 'month',
    price: '19.90',
    currency: 'USD',
    displayPrice: '$19.90',
    priceSuffix: '/mo',
    features: [
      { included: true, description: 'High-fidelity image generation' },
      { included: true, description: 'Precise image editing' },
      { included: true, description: 'Clear text rendering for posters and ads' },
      { included: true, description: 'Stable style consistency across batches' },
      { included: true, description: 'PNG/JPEG export' },
      { included: true, description: 'Commercial Use' },
      { included: true, description: 'Standard Queue' },
      { included: true, description: 'Core workflow tools included' },
    ],
    isHighlighted: false,
    buttonText: 'Get Started',
    displayOrder: 1,
    isActive: true,
    langJsonb: {
      en: {
        cardTitle: 'Standard',
        cardDescription: 'For individuals just getting started.',
        displayPrice: '$19.90',
        priceSuffix: '/mo',
        features: [
          { included: true, description: 'High-fidelity image generation' },
          { included: true, description: 'Precise image editing' },
          { included: true, description: 'Clear text rendering for posters and ads' },
          { included: true, description: 'Stable style consistency across batches' },
          { included: true, description: 'PNG/JPEG export' },
          { included: true, description: 'Commercial Use' },
          { included: true, description: 'Standard Queue' },
          { included: true, description: 'Core workflow tools included' },
        ],
        buttonText: 'Get Started',
      },
      zh: {
        cardTitle: '标准版',
        cardDescription: '适合刚刚起步的个人。',
        displayPrice: '$19.90',
        priceSuffix: '/月',
        features: [
          { included: true, description: '高保真图像生成' },
          { included: true, description: '精细化图像编辑' },
          { included: true, description: '海报与营销文案文字更清晰' },
          { included: true, description: '批量出图风格更稳定' },
          { included: true, description: '支持 PNG/JPEG 导出' },
          { included: true, description: '支持商业用途' },
          { included: true, description: '标准队列' },
          { included: true, description: '包含核心图像工作流能力' },
        ],
        buttonText: 'Get Started',
      },
      ja: {
        cardTitle: 'スタンダード',
        cardDescription: 'これから始める個人向け。',
        displayPrice: '$19.90',
        priceSuffix: '/月',
        features: [
          { included: true, description: '高忠実度の画像生成' },
          { included: true, description: '精密な画像編集' },
          { included: true, description: 'ポスター/広告向けの文字レンダリング' },
          { included: true, description: 'バッチ生成で安定したスタイル一貫性' },
          { included: true, description: 'PNG/JPEG 書き出し' },
          { included: true, description: '商用利用' },
          { included: true, description: '標準キュー' },
          { included: true, description: 'コア画像ワークフロー機能' },
        ],
        buttonText: 'Get Started',
      },
    },
    benefitsJsonb: {
      monthlyCredits: 2800,
      totalMonths: 1,
    },
  },
  {
    id: '880c91b7-451c-4016-8c7b-2462e952843a',
    environment: 'test',
    groupSlug: 'monthly',
    cardTitle: 'Pro',
    cardDescription: 'For creators who need more power.',
    provider: 'paypal',
    paypalProductId: '',
    stripePriceId: 'TODO_UPDATE_STRIPE_PRICE_ID',
    stripeProductId: 'TODO_UPDATE_STRIPE_PRODUCT_ID',
    creemProductId: '',
    paypalPlanId: '',
    paymentType: 'recurring',
    recurringInterval: 'month',
    price: '59.90',
    currency: 'USD',
    displayPrice: '$59.90',
    priceSuffix: '/mo',
    features: [
      { included: true, description: 'High-fidelity image generation' },
      { included: true, description: 'Advanced image editing and local refinements' },
      { included: true, description: 'Clear text rendering for marketing creatives' },
      { included: true, description: 'Stronger style consistency for batch output' },
      { included: true, description: 'PNG/JPEG export' },
      { included: true, description: 'Commercial Use' },
      { included: true, description: 'Fast Generation Queue' },
      { included: true, description: 'Priority Support' },
    ],
    isHighlighted: true,
    highlightText: 'Most Popular',
    buttonText: 'Get Pro',
    displayOrder: 2,
    isActive: true,
    langJsonb: {
      en: {
        cardTitle: 'Pro',
        cardDescription: 'For creators who need more power.',
        displayPrice: '$59.90',
        priceSuffix: '/mo',
        features: [
          { included: true, description: 'High-fidelity image generation' },
          { included: true, description: 'Advanced image editing and local refinements' },
          { included: true, description: 'Clear text rendering for marketing creatives' },
          { included: true, description: 'Stronger style consistency for batch output' },
          { included: true, description: 'PNG/JPEG export' },
          { included: true, description: 'Commercial Use' },
          { included: true, description: 'Fast Generation Queue' },
          { included: true, description: 'Priority Support' },
        ],
        buttonText: 'Get Pro',
        highlightText: 'Most Popular',
      },
      zh: {
        cardTitle: '专业版',
        cardDescription: '适合需要更多功能的创作者。',
        displayPrice: '$59.90',
        priceSuffix: '/月',
        features: [
          { included: true, description: '高保真图像生成' },
          { included: true, description: '高级图像编辑与局部重绘' },
          { included: true, description: '营销素材文字渲染更清晰' },
          { included: true, description: '批量生产风格一致性更强' },
          { included: true, description: '支持 PNG/JPEG 导出' },
          { included: true, description: '支持商业用途' },
          { included: true, description: '快速生成队列' },
          { included: true, description: '优先支持' },
        ],
        buttonText: 'Get Pro',
        highlightText: '最受欢迎',
      },
      ja: {
        cardTitle: 'プロ',
        cardDescription: 'より多くの機能を必要とするクリエイター向け。',
        displayPrice: '$59.90',
        priceSuffix: '/月',
        features: [
          { included: true, description: '高忠実度の画像生成' },
          { included: true, description: '高度な画像編集と部分修正' },
          { included: true, description: 'マーケ素材向けの文字レンダリング' },
          { included: true, description: 'バッチ出力でより強いスタイル一貫性' },
          { included: true, description: 'PNG/JPEG 書き出し' },
          { included: true, description: '商用利用' },
          { included: true, description: '高速生成キュー' },
          { included: true, description: '優先サポート' },
        ],
        buttonText: 'Get Pro',
        highlightText: '一番人気',
      },
    },
    benefitsJsonb: {
      monthlyCredits: 9600,
      totalMonths: 1,
    },
  },
  {
    id: '120dc212-8c67-4bf5-ad0f-f304a1daadbc',
    environment: 'test',
    groupSlug: 'monthly',
    cardTitle: 'Max',
    cardDescription: 'For studios and professionals.',
    provider: 'paypal',
    paypalProductId: '',
    paypalPlanId: '',
    stripePriceId: 'TODO_UPDATE_STRIPE_PRICE_ID',
    stripeProductId: 'TODO_UPDATE_STRIPE_PRODUCT_ID',
    creemProductId: '',
    paymentType: 'recurring',
    recurringInterval: 'month',
    price: '149.90',
    currency: 'USD',
    displayPrice: '$149.90',
    priceSuffix: '/mo',
    features: [
      { included: true, description: 'High-fidelity image generation' },
      { included: true, description: 'Advanced image editing and local refinements' },
      { included: true, description: 'Clear text rendering for complex layouts' },
      { included: true, description: 'Best style consistency for large batches' },
      { included: true, description: 'PNG/JPEG export' },
      { included: true, description: 'Commercial Use' },
      { included: true, description: 'Instant Queue' },
      { included: true, description: 'API Access' },
    ],
    isHighlighted: false,
    buttonText: 'Get Max',
    displayOrder: 3,
    isActive: true,
    langJsonb: {
      en: {
        cardTitle: 'Max',
        cardDescription: 'For studios and professionals.',
        displayPrice: '$149.90',
        priceSuffix: '/mo',
        features: [
          { included: true, description: 'High-fidelity image generation' },
          { included: true, description: 'Advanced image editing and local refinements' },
          { included: true, description: 'Clear text rendering for complex layouts' },
          { included: true, description: 'Best style consistency for large batches' },
          { included: true, description: 'PNG/JPEG export' },
          { included: true, description: 'Commercial Use' },
          { included: true, description: 'Instant Queue' },
          { included: true, description: 'API Access' },
        ],
        buttonText: 'Get Max',
      },
      zh: {
        cardTitle: '终极版',
        cardDescription: '适合工作室和专业人士。',
        displayPrice: '$149.90',
        priceSuffix: '/月',
        features: [
          { included: true, description: '高保真图像生成' },
          { included: true, description: '高级图像编辑与局部重绘' },
          { included: true, description: '复杂排版文字渲染更稳定' },
          { included: true, description: '大规模批量出图风格一致性最佳' },
          { included: true, description: '支持 PNG/JPEG 导出' },
          { included: true, description: '支持商业用途' },
          { included: true, description: '即时队列' },
          { included: true, description: 'API 访问' },
        ],
        buttonText: 'Get Max',
      },
      ja: {
        cardTitle: 'マックス',
        cardDescription: 'スタジオや専門家向け。',
        displayPrice: '$149.90',
        priceSuffix: '/月',
        features: [
          { included: true, description: '高忠実度の画像生成' },
          { included: true, description: '高度な画像編集と部分修正' },
          { included: true, description: '複雑なレイアウトでも安定した文字レンダリング' },
          { included: true, description: '大規模バッチで最高のスタイル一貫性' },
          { included: true, description: 'PNG/JPEG 書き出し' },
          { included: true, description: '商用利用' },
          { included: true, description: '即時キュー' },
          { included: true, description: 'API アクセス' },
        ],
        buttonText: 'Get Max',
      },
    },
    benefitsJsonb: {
      monthlyCredits: 27000,
      totalMonths: 1,
    },
  },

  // ==========================================================================
  // One-Time Plans
  // ==========================================================================
  {
    id: 'a3b924af-0716-40b2-b283-5ee32aaa0100',
    environment: 'test',
    groupSlug: 'onetime',
    cardTitle: 'Standard Pack',
    cardDescription: 'Perfect for trying out.',
    provider: 'paypal',
    stripePriceId: 'TODO_UPDATE_STRIPE_PRICE_ID',
    stripeProductId: 'TODO_UPDATE_STRIPE_PRODUCT_ID',
    creemProductId: '',
    paymentType: 'one_time',
    recurringInterval: null,
    price: '9.90',
    currency: 'USD',
    displayPrice: '$9.90',
    priceSuffix: '',
    features: [
      { included: true, description: '1,000 Credits' },
      { included: true, description: 'Never expire' },
    ],
    isHighlighted: false,
    buttonText: 'Buy Now',
    displayOrder: 1,
    isActive: true,
    langJsonb: {
      en: {
        cardTitle: 'Standard Pack',
        cardDescription: 'Perfect for trying out.',
        displayPrice: '$9.90',
        features: [
          { included: true, description: '1,000 Credits' },
          { included: true, description: 'Never expire' },
        ],
        buttonText: 'Buy Now',
      },
      zh: {
        cardTitle: '标准包',
        cardDescription: '适合尝试。',
        displayPrice: '$9.90',
        features: [
          { included: true, description: '1,000 积分' },
          { included: true, description: '永不过期' },
        ],
        buttonText: '立即购买',
      },
      ja: {
        cardTitle: 'スタンダードパック',
        cardDescription: 'お試しに最適。',
        displayPrice: '$9.90',
        features: [
          { included: true, description: '1,000 クレジット' },
          { included: true, description: '有効期限なし' },
        ],
        buttonText: '今すぐ購入',
      },
    },
    benefitsJsonb: {
      oneTimeCredits: 1000,
    },
  },
  {
    id: 'e9ca7da0-941d-4ad7-b0b7-5d3e95498c36',
    environment: 'test',
    groupSlug: 'onetime',
    cardTitle: 'Pro Pack',
    cardDescription: 'Most popular choice.',
    provider: 'paypal',
    stripePriceId: 'TODO_UPDATE_STRIPE_PRICE_ID',
    stripeProductId: 'TODO_UPDATE_STRIPE_PRODUCT_ID',
    creemProductId: '',
    paymentType: 'one_time',
    recurringInterval: null,
    price: '29.90',
    currency: 'USD',
    displayPrice: '$29.90',
    priceSuffix: '',
    features: [
      { included: true, description: '3,750 Credits' },
      { included: true, description: 'Never expire' },
      { included: true, description: 'Priority Generation' },
    ],
    isHighlighted: true,
    highlightText: 'Best Value',
    buttonText: 'Buy Now',
    displayOrder: 2,
    isActive: true,
    langJsonb: {
      en: {
        cardTitle: 'Pro Pack',
        cardDescription: 'Most popular choice.',
        displayPrice: '$29.90',
        features: [
          { included: true, description: '3,750 Credits' },
          { included: true, description: 'Never expire' },
          { included: true, description: 'Priority Generation' },
        ],
        buttonText: 'Buy Now',
        highlightText: 'Best Value',
      },
      zh: {
        cardTitle: '专业包',
        cardDescription: '最受欢迎的选择。',
        displayPrice: '$29.90',
        features: [
          { included: true, description: '3,750 积分' },
          { included: true, description: '永不过期' },
          { included: true, description: '优先生成' },
        ],
        buttonText: '立即购买',
        highlightText: '超值推荐',
      },
      ja: {
        cardTitle: 'プロパック',
        cardDescription: '一番人気の選択。',
        displayPrice: '$29.90',
        features: [
          { included: true, description: '3,750 クレジット' },
          { included: true, description: '有効期限なし' },
          { included: true, description: '優先生成' },
        ],
        buttonText: '今すぐ購入',
        highlightText: 'ベストバリュー',
      },
    },
    benefitsJsonb: {
      oneTimeCredits: 3750,
    },
  },
  {
    id: '8e19535a-ae94-4895-b1ed-e95c9022791d',
    environment: 'test',
    groupSlug: 'onetime',
    cardTitle: 'Max Pack',
    cardDescription: 'For heavy users.',
    provider: 'paypal',
    stripePriceId: 'TODO_UPDATE_STRIPE_PRICE_ID',
    stripeProductId: 'TODO_UPDATE_STRIPE_PRODUCT_ID',
    creemProductId: '',
    paymentType: 'one_time',
    recurringInterval: null,
    price: '79.90',
    currency: 'USD',
    displayPrice: '$79.90',
    priceSuffix: '',
    features: [
      { included: true, description: '12,000 Credits' },
      { included: true, description: 'Never expire' },
      { included: true, description: 'Priority Generation' },
    ],
    isHighlighted: false,
    buttonText: 'Buy Now',
    displayOrder: 3,
    isActive: true,
    langJsonb: {
      en: {
        cardTitle: 'Max Pack',
        cardDescription: 'For heavy users.',
        displayPrice: '$79.90',
        features: [
          { included: true, description: '12,000 Credits' },
          { included: true, description: 'Never expire' },
          { included: true, description: 'Priority Generation' },
        ],
        buttonText: 'Buy Now',
      },
      zh: {
        cardTitle: '终极包',
        cardDescription: '适合重度用户。',
        displayPrice: '$79.90',
        features: [
          { included: true, description: '12,000 积分' },
          { included: true, description: '永不过期' },
          { included: true, description: '优先生成' },
        ],
        buttonText: '立即购买',
      },
      ja: {
        cardTitle: 'マックスパック',
        cardDescription: 'ヘビーユーザー向け。',
        displayPrice: '$79.90',
        features: [
          { included: true, description: '12,000 クレジット' },
          { included: true, description: '有効期限なし' },
          { included: true, description: '優先生成' },
        ],
        buttonText: '今すぐ購入',
      },
    },
    benefitsJsonb: {
      oneTimeCredits: 12000,
    },
  },
]

export const pricingPlans: PricingPlanConfig[] = [
  ... testPricingPlans,
  // ==========================================================================
  // Annual Plans
  // ==========================================================================
  {
    id: '58f8aa44-b082-4f7d-93f0-e11d0e25b817',
    environment: 'live',
    groupSlug: 'annual',
    cardTitle: 'Standard',
    cardDescription: 'For individuals just getting started.',
    provider: 'paypal',
    paypalProductId: '',
    paypalPlanId: '',
    stripePriceId: 'TODO_UPDATE_STRIPE_PRICE_ID',
    stripeProductId: 'TODO_UPDATE_STRIPE_PRODUCT_ID',
    creemProductId: '',
    paymentType: 'recurring',
    recurringInterval: 'year',
    price: '118.80',
    currency: 'USD',
    displayPrice: '$9.90',
    priceSuffix: '/mo',
    features: [
      { included: true, description: 'High-fidelity image generation' },
      { included: true, description: 'Precise image editing' },
      { included: true, description: 'Clear text rendering for posters and ads' },
      { included: true, description: 'Stable style consistency across batches' },
      { included: true, description: 'PNG/JPEG export' },
      { included: true, description: 'Commercial Use' },
      { included: true, description: 'Standard Queue' },
      { included: true, description: 'Core workflow tools included' },
    ],
    isHighlighted: false,
    buttonText: 'Get Started',
    displayOrder: 1,
    isActive: true,
    langJsonb: {
      en: {
        cardTitle: 'Standard',
        cardDescription: 'For individuals just getting started.',
        displayPrice: '$9.90',
        priceSuffix: '/mo',
        features: [
          { included: true, description: 'High-fidelity image generation' },
          { included: true, description: 'Precise image editing' },
          { included: true, description: 'Clear text rendering for posters and ads' },
          { included: true, description: 'Stable style consistency across batches' },
          { included: true, description: 'PNG/JPEG export' },
          { included: true, description: 'Commercial Use' },
          { included: true, description: 'Standard Queue' },
          { included: true, description: 'Core workflow tools included' },
        ],
        buttonText: 'Get Started',
      },
      zh: {
        cardTitle: '标准版',
        cardDescription: '适合刚刚起步的个人。',
        displayPrice: '$9.90',
        priceSuffix: '/月',
        features: [
          { included: true, description: '高保真图像生成' },
          { included: true, description: '精细化图像编辑' },
          { included: true, description: '海报与营销文案文字更清晰' },
          { included: true, description: '批量出图风格更稳定' },
          { included: true, description: '支持 PNG/JPEG 导出' },
          { included: true, description: '支持商业用途' },
          { included: true, description: '标准队列' },
          { included: true, description: '包含核心图像工作流能力' },
        ],
        buttonText: 'Get Started',
      },
      ja: {
        cardTitle: 'スタンダード',
        cardDescription: 'これから始める個人向け。',
        displayPrice: '$9.90',
        priceSuffix: '/月',
        features: [
          { included: true, description: '高忠実度の画像生成' },
          { included: true, description: '精密な画像編集' },
          { included: true, description: 'ポスター/広告向けの文字レンダリング' },
          { included: true, description: 'バッチ生成で安定したスタイル一貫性' },
          { included: true, description: 'PNG/JPEG 書き出し' },
          { included: true, description: '商用利用' },
          { included: true, description: '標準キュー' },
          { included: true, description: 'コア画像ワークフロー機能' },
        ],
        buttonText: 'Get Started',
      },
    },
    benefitsJsonb: {
      monthlyCredits: 1600,
      totalMonths: 12,
    },
  },
  {
    id: '5b5766c1-f208-40eb-a43f-82a861873e27',
    environment: 'live',
    groupSlug: 'annual',
    cardTitle: 'Pro',
    cardDescription: 'For creators who need more power.',
    provider: 'paypal',
    paypalProductId: '',
    paypalPlanId: '',
    stripePriceId: 'TODO_UPDATE_STRIPE_PRICE_ID',
    stripeProductId: 'TODO_UPDATE_STRIPE_PRODUCT_ID',
    creemProductId: '',
    paymentType: 'recurring',
    recurringInterval: 'year',
    price: '358.80',
    currency: 'USD',
    displayPrice: '$29.90',
    priceSuffix: '/mo',
    features: [
      { included: true, description: 'High-fidelity image generation' },
      { included: true, description: 'Advanced image editing and local refinements' },
      { included: true, description: 'Clear text rendering for marketing creatives' },
      { included: true, description: 'Stronger style consistency for batch output' },
      { included: true, description: 'PNG/JPEG export' },
      { included: true, description: 'Commercial Use' },
      { included: true, description: 'Fast Generation Queue' },
      { included: true, description: 'Priority Support' },
    ],
    isHighlighted: true,
    highlightText: 'Most Popular',
    buttonText: 'Get Pro',
    displayOrder: 2,
    isActive: true,
    langJsonb: {
      en: {
        cardTitle: 'Pro',
        cardDescription: 'For creators who need more power.',
        displayPrice: '$29.90',
        priceSuffix: '/mo',
        features: [
          { included: true, description: 'High-fidelity image generation' },
          { included: true, description: 'Advanced image editing and local refinements' },
          { included: true, description: 'Clear text rendering for marketing creatives' },
          { included: true, description: 'Stronger style consistency for batch output' },
          { included: true, description: 'PNG/JPEG export' },
          { included: true, description: 'Commercial Use' },
          { included: true, description: 'Fast Generation Queue' },
          { included: true, description: 'Priority Support' },
        ],
        buttonText: 'Get Pro',
        highlightText: 'Most Popular',
      },
      zh: {
        cardTitle: '专业版',
        cardDescription: '适合需要更多功能的创作者。',
        displayPrice: '$29.90',
        priceSuffix: '/月',
        features: [
          { included: true, description: '高保真图像生成' },
          { included: true, description: '高级图像编辑与局部重绘' },
          { included: true, description: '营销素材文字渲染更清晰' },
          { included: true, description: '批量生产风格一致性更强' },
          { included: true, description: '支持 PNG/JPEG 导出' },
          { included: true, description: '支持商业用途' },
          { included: true, description: '快速生成队列' },
          { included: true, description: '优先支持' },
        ],
        buttonText: 'Get Pro',
        highlightText: '最受欢迎',
      },
      ja: {
        cardTitle: 'プロ',
        cardDescription: 'より多くの機能を必要とするクリエイター向け。',
        displayPrice: '$29.90',
        priceSuffix: '/月',
        features: [
          { included: true, description: '高忠実度の画像生成' },
          { included: true, description: '高度な画像編集と部分修正' },
          { included: true, description: 'マーケ素材向けの文字レンダリング' },
          { included: true, description: 'バッチ出力でより強いスタイル一貫性' },
          { included: true, description: 'PNG/JPEG 書き出し' },
          { included: true, description: '商用利用' },
          { included: true, description: '高速生成キュー' },
          { included: true, description: '優先サポート' },
        ],
        buttonText: 'Get Pro',
        highlightText: '一番人気',
      },
    },
    benefitsJsonb: {
      monthlyCredits: 5400,
      totalMonths: 12,
    },
  },
  {
    id: 'f145c46a-184f-4d35-8deb-755e229b2fb5',
    environment: 'live',
    groupSlug: 'annual',
    cardTitle: 'Max',
    cardDescription: 'For studios and professionals.',
    provider: 'paypal',
    paypalProductId: '',
    paypalPlanId: '',
    stripePriceId: 'TODO_UPDATE_STRIPE_PRICE_ID',
    stripeProductId: 'TODO_UPDATE_STRIPE_PRODUCT_ID',
    creemProductId: '',
    paymentType: 'recurring',
    recurringInterval: 'year',
    price: '958.80',
    currency: 'USD',
    displayPrice: '$79.90',
    priceSuffix: '/mo',
    features: [
      { included: true, description: 'High-fidelity image generation' },
      { included: true, description: 'Advanced image editing and local refinements' },
      { included: true, description: 'Clear text rendering for complex layouts' },
      { included: true, description: 'Best style consistency for large batches' },
      { included: true, description: 'PNG/JPEG export' },
      { included: true, description: 'Commercial Use' },
      { included: true, description: 'Instant Queue' },
      { included: true, description: 'API Access' },
    ],
    isHighlighted: false,
    buttonText: 'Get Max',
    displayOrder: 3,
    isActive: true,
    langJsonb: {
      en: {
        cardTitle: 'Max',
        cardDescription: 'For studios and professionals.',
        displayPrice: '$79.90',
        priceSuffix: '/mo',
        features: [
          { included: true, description: 'High-fidelity image generation' },
          { included: true, description: 'Advanced image editing and local refinements' },
          { included: true, description: 'Clear text rendering for complex layouts' },
          { included: true, description: 'Best style consistency for large batches' },
          { included: true, description: 'PNG/JPEG export' },
          { included: true, description: 'Commercial Use' },
          { included: true, description: 'Instant Queue' },
          { included: true, description: 'API Access' },
        ],
        buttonText: 'Get Max',
      },
      zh: {
        cardTitle: '终极版',
        cardDescription: '适合工作室和专业人士。',
        displayPrice: '$79.90',
        priceSuffix: '/月',
        features: [
          { included: true, description: '高保真图像生成' },
          { included: true, description: '高级图像编辑与局部重绘' },
          { included: true, description: '复杂排版文字渲染更稳定' },
          { included: true, description: '大规模批量出图风格一致性最佳' },
          { included: true, description: '支持 PNG/JPEG 导出' },
          { included: true, description: '支持商业用途' },
          { included: true, description: '即时队列' },
          { included: true, description: 'API 访问' },
        ],
        buttonText: 'Get Max',
      },
      ja: {
        cardTitle: 'マックス',
        cardDescription: 'スタジオや専門家向け。',
        displayPrice: '$79.90',
        priceSuffix: '/月',
        features: [
          { included: true, description: '高忠実度の画像生成' },
          { included: true, description: '高度な画像編集と部分修正' },
          { included: true, description: '複雑なレイアウトでも安定した文字レンダリング' },
          { included: true, description: '大規模バッチで最高のスタイル一貫性' },
          { included: true, description: 'PNG/JPEG 書き出し' },
          { included: true, description: '商用利用' },
          { included: true, description: '即時キュー' },
          { included: true, description: 'API アクセス' },
        ],
        buttonText: 'Get Max',
      },
    },
    benefitsJsonb: {
      monthlyCredits: 16000,
      totalMonths: 12,
    },
  },

  // ==========================================================================
  // Monthly Plans
  // ==========================================================================
  {
    id: '77788688-aaa4-47bc-9b65-03766b884004',
    environment: 'live',
    groupSlug: 'monthly',
    cardTitle: 'Standard',
    cardDescription: 'For individuals just getting started.',
    provider: 'paypal',
    paypalProductId: '',
    paypalPlanId: '',
    stripePriceId: 'TODO_UPDATE_STRIPE_PRICE_ID',
    stripeProductId: 'TODO_UPDATE_STRIPE_PRODUCT_ID',
    creemProductId: '',
    paymentType: 'recurring',
    recurringInterval: 'month',
    price: '19.90',
    currency: 'USD',
    displayPrice: '$19.90',
    priceSuffix: '/mo',
    features: [
      { included: true, description: 'High-fidelity image generation' },
      { included: true, description: 'Precise image editing' },
      { included: true, description: 'Clear text rendering for posters and ads' },
      { included: true, description: 'Stable style consistency across batches' },
      { included: true, description: 'PNG/JPEG export' },
      { included: true, description: 'Commercial Use' },
      { included: true, description: 'Standard Queue' },
      { included: true, description: 'Core workflow tools included' },
    ],
    isHighlighted: false,
    buttonText: 'Get Started',
    displayOrder: 1,
    isActive: true,
    langJsonb: {
      en: {
        cardTitle: 'Standard',
        cardDescription: 'For individuals just getting started.',
        displayPrice: '$19.90',
        priceSuffix: '/mo',
        features: [
          { included: true, description: 'High-fidelity image generation' },
          { included: true, description: 'Precise image editing' },
          { included: true, description: 'Clear text rendering for posters and ads' },
          { included: true, description: 'Stable style consistency across batches' },
          { included: true, description: 'PNG/JPEG export' },
          { included: true, description: 'Commercial Use' },
          { included: true, description: 'Standard Queue' },
          { included: true, description: 'Core workflow tools included' },
        ],
        buttonText: 'Get Started',
      },
      zh: {
        cardTitle: '标准版',
        cardDescription: '适合刚刚起步的个人。',
        displayPrice: '$19.90',
        priceSuffix: '/月',
        features: [
          { included: true, description: '高保真图像生成' },
          { included: true, description: '精细化图像编辑' },
          { included: true, description: '海报与营销文案文字更清晰' },
          { included: true, description: '批量出图风格更稳定' },
          { included: true, description: '支持 PNG/JPEG 导出' },
          { included: true, description: '支持商业用途' },
          { included: true, description: '标准队列' },
          { included: true, description: '包含核心图像工作流能力' },
        ],
        buttonText: 'Get Started',
      },
      ja: {
        cardTitle: 'スタンダード',
        cardDescription: 'これから始める個人向け。',
        displayPrice: '$19.90',
        priceSuffix: '/月',
        features: [
          { included: true, description: '高忠実度の画像生成' },
          { included: true, description: '精密な画像編集' },
          { included: true, description: 'ポスター/広告向けの文字レンダリング' },
          { included: true, description: 'バッチ生成で安定したスタイル一貫性' },
          { included: true, description: 'PNG/JPEG 書き出し' },
          { included: true, description: '商用利用' },
          { included: true, description: '標準キュー' },
          { included: true, description: 'コア画像ワークフロー機能' },
        ],
        buttonText: 'Get Started',
      },
    },
    benefitsJsonb: {
      monthlyCredits: 2800,
      totalMonths: 1,
    },
  },
  {
    id: '3b7c86d3-e32b-487a-bddf-aa9c15f6ec5c',
    environment: 'live',
    groupSlug: 'monthly',
    cardTitle: 'Pro',
    cardDescription: 'For creators who need more power.',
    provider: 'paypal',
    paypalProductId: '',
    paypalPlanId: '',
    stripePriceId: 'TODO_UPDATE_STRIPE_PRICE_ID',
    stripeProductId: 'TODO_UPDATE_STRIPE_PRODUCT_ID',
    creemProductId: '',
    paymentType: 'recurring',
    recurringInterval: 'month',
    price: '59.90',
    currency: 'USD',
    displayPrice: '$59.90',
    priceSuffix: '/mo',
    features: [
      { included: true, description: 'High-fidelity image generation' },
      { included: true, description: 'Advanced image editing and local refinements' },
      { included: true, description: 'Clear text rendering for marketing creatives' },
      { included: true, description: 'Stronger style consistency for batch output' },
      { included: true, description: 'PNG/JPEG export' },
      { included: true, description: 'Commercial Use' },
      { included: true, description: 'Fast Generation Queue' },
      { included: true, description: 'Priority Support' },
    ],
    isHighlighted: true,
    highlightText: 'Most Popular',
    buttonText: 'Get Pro',
    displayOrder: 2,
    isActive: true,
    langJsonb: {
      en: {
        cardTitle: 'Pro',
        cardDescription: 'For creators who need more power.',
        displayPrice: '$59.90',
        priceSuffix: '/mo',
        features: [
          { included: true, description: 'High-fidelity image generation' },
          { included: true, description: 'Advanced image editing and local refinements' },
          { included: true, description: 'Clear text rendering for marketing creatives' },
          { included: true, description: 'Stronger style consistency for batch output' },
          { included: true, description: 'PNG/JPEG export' },
          { included: true, description: 'Commercial Use' },
          { included: true, description: 'Fast Generation Queue' },
          { included: true, description: 'Priority Support' },
        ],
        buttonText: 'Get Pro',
        highlightText: 'Most Popular',
      },
      zh: {
        cardTitle: '专业版',
        cardDescription: '适合需要更多功能的创作者。',
        displayPrice: '$59.90',
        priceSuffix: '/月',
        features: [
          { included: true, description: '高保真图像生成' },
          { included: true, description: '高级图像编辑与局部重绘' },
          { included: true, description: '营销素材文字渲染更清晰' },
          { included: true, description: '批量生产风格一致性更强' },
          { included: true, description: '支持 PNG/JPEG 导出' },
          { included: true, description: '支持商业用途' },
          { included: true, description: '快速生成队列' },
          { included: true, description: '优先支持' },
        ],
        buttonText: 'Get Pro',
        highlightText: '最受欢迎',
      },
      ja: {
        cardTitle: 'プロ',
        cardDescription: 'より多くの機能を必要とするクリエイター向け。',
        displayPrice: '$59.90',
        priceSuffix: '/月',
        features: [
          { included: true, description: '高忠実度の画像生成' },
          { included: true, description: '高度な画像編集と部分修正' },
          { included: true, description: 'マーケ素材向けの文字レンダリング' },
          { included: true, description: 'バッチ出力でより強いスタイル一貫性' },
          { included: true, description: 'PNG/JPEG 書き出し' },
          { included: true, description: '商用利用' },
          { included: true, description: '高速生成キュー' },
          { included: true, description: '優先サポート' },
        ],
        buttonText: 'Get Pro',
        highlightText: '一番人気',
      },
    },
    benefitsJsonb: {
      monthlyCredits: 9600,
      totalMonths: 1,
    },
  },
  {
    id: '3aa5b610-f217-4018-98f3-ebe11512c14e',
    environment: 'live',
    groupSlug: 'monthly',
    cardTitle: 'Max',
    cardDescription: 'For studios and professionals.',
    provider: 'paypal',
    paypalProductId: '',
    paypalPlanId: '',
    stripePriceId: 'TODO_UPDATE_STRIPE_PRICE_ID',
    stripeProductId: 'TODO_UPDATE_STRIPE_PRODUCT_ID',
    creemProductId: '',
    paymentType: 'recurring',
    recurringInterval: 'month',
    price: '149.90',
    currency: 'USD',
    displayPrice: '$149.90',
    priceSuffix: '/mo',
    features: [
      { included: true, description: 'High-fidelity image generation' },
      { included: true, description: 'Advanced image editing and local refinements' },
      { included: true, description: 'Clear text rendering for complex layouts' },
      { included: true, description: 'Best style consistency for large batches' },
      { included: true, description: 'PNG/JPEG export' },
      { included: true, description: 'Commercial Use' },
      { included: true, description: 'Instant Queue' },
      { included: true, description: 'API Access' },
    ],
    isHighlighted: false,
    buttonText: 'Get Max',
    displayOrder: 3,
    isActive: true,
    langJsonb: {
      en: {
        cardTitle: 'Max',
        cardDescription: 'For studios and professionals.',
        displayPrice: '$149.90',
        priceSuffix: '/mo',
        features: [
          { included: true, description: 'High-fidelity image generation' },
          { included: true, description: 'Advanced image editing and local refinements' },
          { included: true, description: 'Clear text rendering for complex layouts' },
          { included: true, description: 'Best style consistency for large batches' },
          { included: true, description: 'PNG/JPEG export' },
          { included: true, description: 'Commercial Use' },
          { included: true, description: 'Instant Queue' },
          { included: true, description: 'API Access' },
        ],
        buttonText: 'Get Max',
      },
      zh: {
        cardTitle: '终极版',
        cardDescription: '适合工作室和专业人士。',
        displayPrice: '$149.90',
        priceSuffix: '/月',
        features: [
          { included: true, description: '高保真图像生成' },
          { included: true, description: '高级图像编辑与局部重绘' },
          { included: true, description: '复杂排版文字渲染更稳定' },
          { included: true, description: '大规模批量出图风格一致性最佳' },
          { included: true, description: '支持 PNG/JPEG 导出' },
          { included: true, description: '支持商业用途' },
          { included: true, description: '即时队列' },
          { included: true, description: 'API 访问' },
        ],
        buttonText: 'Get Max',
      },
      ja: {
        cardTitle: 'マックス',
        cardDescription: 'スタジオや専門家向け。',
        displayPrice: '$149.90',
        priceSuffix: '/月',
        features: [
          { included: true, description: '高忠実度の画像生成' },
          { included: true, description: '高度な画像編集と部分修正' },
          { included: true, description: '複雑なレイアウトでも安定した文字レンダリング' },
          { included: true, description: '大規模バッチで最高のスタイル一貫性' },
          { included: true, description: 'PNG/JPEG 書き出し' },
          { included: true, description: '商用利用' },
          { included: true, description: '即時キュー' },
          { included: true, description: 'API アクセス' },
        ],
        buttonText: 'Get Max',
      },
    },
    benefitsJsonb: {
      monthlyCredits: 27000,
      totalMonths: 1,
    },
  },

  // ==========================================================================
  // One-Time Plans
  // ==========================================================================
  {
    id: 'cb4ea773-5ef5-4f0b-b9ec-312e267e9b7f',
    environment: 'live',
    groupSlug: 'onetime',
    cardTitle: 'Standard Pack',
    cardDescription: 'Perfect for trying out.',
    provider: 'paypal',
    stripePriceId: 'TODO_UPDATE_STRIPE_PRICE_ID',
    stripeProductId: 'TODO_UPDATE_STRIPE_PRODUCT_ID',
    creemProductId: '',
    paymentType: 'one_time',
    recurringInterval: null,
    price: '9.90',
    currency: 'USD',
    displayPrice: '$9.90',
    priceSuffix: '',
    features: [
      { included: true, description: '1,000 Credits' },
      { included: true, description: 'Never expire' },
    ],
    isHighlighted: false,
    buttonText: 'Buy Now',
    displayOrder: 1,
    isActive: true,
    langJsonb: {
      en: {
        cardTitle: 'Standard Pack',
        cardDescription: 'Perfect for trying out.',
        displayPrice: '$9.90',
        features: [
          { included: true, description: '1,000 Credits' },
          { included: true, description: 'Never expire' },
        ],
        buttonText: 'Buy Now',
      },
      zh: {
        cardTitle: '标准包',
        cardDescription: '适合尝试。',
        displayPrice: '$9.90',
        features: [
          { included: true, description: '1,000 积分' },
          { included: true, description: '永不过期' },
        ],
        buttonText: '立即购买',
      },
      ja: {
        cardTitle: 'スタンダードパック',
        cardDescription: 'お試しに最適。',
        displayPrice: '$9.90',
        features: [
          { included: true, description: '1,000 クレジット' },
          { included: true, description: '有効期限なし' },
        ],
        buttonText: '今すぐ購入',
      },
    },
    benefitsJsonb: {
      oneTimeCredits: 1000,
    },
  },
  {
    id: 'c249ea2b-d412-4ee5-ae8b-f8b00321c96a',
    environment: 'live',
    groupSlug: 'onetime',
    cardTitle: 'Pro Pack',
    cardDescription: 'Most popular choice.',
    provider: 'paypal',
    stripePriceId: 'TODO_UPDATE_STRIPE_PRICE_ID',
    stripeProductId: 'TODO_UPDATE_STRIPE_PRODUCT_ID',
    creemProductId: '',
    paymentType: 'one_time',
    recurringInterval: null,
    price: '29.90',
    currency: 'USD',
    displayPrice: '$29.90',
    priceSuffix: '',
    features: [
      { included: true, description: '3,750 Credits' },
      { included: true, description: 'Never expire' },
      { included: true, description: 'Priority Generation' },
    ],
    isHighlighted: true,
    highlightText: 'Best Value',
    buttonText: 'Buy Now',
    displayOrder: 2,
    isActive: true,
    langJsonb: {
      en: {
        cardTitle: 'Pro Pack',
        cardDescription: 'Most popular choice.',
        displayPrice: '$29.90',
        features: [
          { included: true, description: '3,750 Credits' },
          { included: true, description: 'Never expire' },
          { included: true, description: 'Priority Generation' },
        ],
        buttonText: 'Buy Now',
        highlightText: 'Best Value',
      },
      zh: {
        cardTitle: '专业包',
        cardDescription: '最受欢迎的选择。',
        displayPrice: '$29.90',
        features: [
          { included: true, description: '3,750 积分' },
          { included: true, description: '永不过期' },
          { included: true, description: '优先生成' },
        ],
        buttonText: '立即购买',
        highlightText: '超值推荐',
      },
      ja: {
        cardTitle: 'プロパック',
        cardDescription: '一番人気の選択。',
        displayPrice: '$29.90',
        features: [
          { included: true, description: '3,750 クレジット' },
          { included: true, description: '有効期限なし' },
          { included: true, description: '優先生成' },
        ],
        buttonText: '今すぐ購入',
        highlightText: 'ベストバリュー',
      },
    },
    benefitsJsonb: {
      oneTimeCredits: 3750,
    },
  },
  {
    id: 'e34c4e96-a0ba-4d0f-a5e1-99bfe1c9def0',
    environment: 'live',
    groupSlug: 'onetime',
    cardTitle: 'Max Pack',
    cardDescription: 'For heavy users.',
    provider: 'paypal',
    stripePriceId: 'TODO_UPDATE_STRIPE_PRICE_ID',
    stripeProductId: 'TODO_UPDATE_STRIPE_PRODUCT_ID',
    creemProductId: '',
    paymentType: 'one_time',
    recurringInterval: null,
    price: '79.90',
    currency: 'USD',
    displayPrice: '$79.90',
    priceSuffix: '',
    features: [
      { included: true, description: '12,000 Credits' },
      { included: true, description: 'Never expire' },
      { included: true, description: 'Priority Generation' },
    ],
    isHighlighted: false,
    buttonText: 'Buy Now',
    displayOrder: 3,
    isActive: true,
    langJsonb: {
      en: {
        cardTitle: 'Max Pack',
        cardDescription: 'For heavy users.',
        displayPrice: '$79.90',
        features: [
          { included: true, description: '12,000 Credits' },
          { included: true, description: 'Never expire' },
          { included: true, description: 'Priority Generation' },
        ],
        buttonText: 'Buy Now',
      },
      zh: {
        cardTitle: '终极包',
        cardDescription: '适合重度用户。',
        displayPrice: '$79.90',
        features: [
          { included: true, description: '12,000 积分' },
          { included: true, description: '永不过期' },
          { included: true, description: '优先生成' },
        ],
        buttonText: '立即购买',
      },
      ja: {
        cardTitle: 'マックスパック',
        cardDescription: 'ヘビーユーザー向け。',
        displayPrice: '$79.90',
        features: [
          { included: true, description: '12,000 クレジット' },
          { included: true, description: '有効期限なし' },
          { included: true, description: '優先生成' },
        ],
        buttonText: '今すぐ購入',
      },
    },
    benefitsJsonb: {
      oneTimeCredits: 12000,
    },
  },
]
