/**
 * Build-time blog data generator
 * 
 * This script runs during the build process to pre-read all MDX blog files
 * and generate a TypeScript data file. This allows Cloudflare Workers to serve
 * local blog content without filesystem access.
 */

import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';

interface BlogPostData {
  slug: string;
  title: string;
  description: string;
  tags: string;
  featuredImageUrl: string;
  publishedAt: string;
  status: 'draft' | 'published' | 'archived';
  visibility: 'public' | 'logged_in' | 'subscribers';
  isPinned: boolean;
  content: string;
  locale: string;
}

interface BlogData {
  [locale: string]: BlogPostData[];
}

const BLOGS_DIR = path.join(process.cwd(), 'blogs');
const OUTPUT_FILE = path.join(process.cwd(), 'lib', 'cms', 'blog-data.ts');

function generateBlogData(): BlogData {
  const data: BlogData = {};

  // Check if blogs directory exists
  if (!fs.existsSync(BLOGS_DIR)) {
    console.log('No blogs directory found, skipping blog data generation');
    return data;
  }

  // Get all locale directories
  const locales = fs.readdirSync(BLOGS_DIR).filter(item => {
    const itemPath = path.join(BLOGS_DIR, item);
    return fs.statSync(itemPath).isDirectory();
  });

  for (const locale of locales) {
    const localeDir = path.join(BLOGS_DIR, locale);
    data[locale] = [];

    // Get all MDX files in the locale directory
    const files = fs.readdirSync(localeDir).filter(file => 
      file.endsWith('.mdx') || file.endsWith('.md')
    );

    for (const file of files) {
      const filePath = path.join(localeDir, file);
      const fileContents = fs.readFileSync(filePath, 'utf8');
      const { data: frontmatter, content } = matter(fileContents);

      // Skip drafts if needed (we include all but filter at runtime)
      const post: BlogPostData = {
        slug: frontmatter.slug || '',
        title: frontmatter.title || '',
        description: frontmatter.description || '',
        tags: frontmatter.tags || '',
        featuredImageUrl: frontmatter.featuredImageUrl || '',
        publishedAt: frontmatter.publishedAt || new Date().toISOString(),
        status: frontmatter.status || 'published',
        visibility: frontmatter.visibility || 'public',
        isPinned: frontmatter.isPinned || false,
        content,
        locale,
      };

      data[locale].push(post);
    }

    // Sort posts: pinned first, then by publishedAt desc
    data[locale].sort((a, b) => {
      if (a.isPinned !== b.isPinned) {
        return (b.isPinned ? 1 : 0) - (a.isPinned ? 1 : 0);
      }
      return new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime();
    });

    console.log(`✓ Generated data for ${locale}: ${data[locale].length} posts`);
  }

  return data;
}

function generateTypeScriptFile(data: BlogData): string {
  return `/**
 * Auto-generated blog data for Cloudflare Workers
 * Generated at: ${new Date().toISOString()}
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Run \`pnpm blog:build-data\` to regenerate
 */

export interface BlogPostData {
  slug: string;
  title: string;
  description: string;
  tags: string;
  featuredImageUrl: string;
  publishedAt: string;
  status: 'draft' | 'published' | 'archived';
  visibility: 'public' | 'logged_in' | 'subscribers';
  isPinned: boolean;
  content: string;
  locale: string;
}

export const blogData: { [locale: string]: BlogPostData[] } = ${JSON.stringify(data, null, 2)};
`;
}

function main() {
  console.log('Generating blog data for Cloudflare Workers...');
  
  const blogData = generateBlogData();
  
  // Ensure output directory exists
  const outputDir = path.dirname(OUTPUT_FILE);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // Write TypeScript file
  const tsContent = generateTypeScriptFile(blogData);
  fs.writeFileSync(OUTPUT_FILE, tsContent);
  
  console.log(`✓ Blog data written to ${OUTPUT_FILE}`);
}

main();
