/**
 * Auto-generated blog data for Cloudflare Workers
 * Generated at: 2026-04-14T06:24:49.094Z
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Run `pnpm blog:build-data` to regenerate
 */

export interface BlogPostData {
  slug: string;
  title: string;
  description: string;
  tags: string;
  featuredImageUrl: string;
  publishedAt: string;
  status: 'draft' | 'published' | 'archived';
  visibility: 'public' | 'logged_in' | 'subscribers';
  isPinned: boolean;
  content: string;
  locale: string;
}

export const blogData: { [locale: string]: BlogPostData[] } = {
  "en": [
    {
      "slug": "/demo",
      "title": "demo",
      "description": "it is a description",
      "tags": "nextjs,i18n,mdx,starter,robots,sitemap",
      "featuredImageUrl": "",
      "publishedAt": "2025-02-16T00:00:00.000Z",
      "status": "draft",
      "visibility": "public",
      "isPinned": false,
      "content": "\n## Introduction\n\ndemo\n\n## How to use\n\ndemo",
      "locale": "en"
    }
  ],
  "ja": [
    {
      "slug": "/demo",
      "title": "デモ",
      "description": "これはデモプロジェクトの説明です",
      "tags": "nextjs,i18n,mdx,starter,robots,sitemap",
      "featuredImageUrl": "",
      "publishedAt": "2025-02-16T00:00:00.000Z",
      "status": "draft",
      "visibility": "public",
      "isPinned": false,
      "content": "\n## はじめに\n\nデモ\n\n## 使い方\n\nデモ",
      "locale": "ja"
    }
  ],
  "zh": [
    {
      "slug": "/demo2",
      "title": "示例2",
      "description": "这是一个描述2",
      "tags": "nextjs,i18n,mdx,starter,robots,sitemap",
      "featuredImageUrl": "",
      "publishedAt": "2025-02-17T00:00:00.000Z",
      "status": "draft",
      "visibility": "public",
      "isPinned": false,
      "content": "\n## 简介\n\n示例2\n\n## 如何使用\n\n示例2",
      "locale": "zh"
    },
    {
      "slug": "/demo",
      "title": "示例",
      "description": "这是一个描述",
      "tags": "nextjs,i18n,mdx,starter,robots,sitemap",
      "featuredImageUrl": "",
      "publishedAt": "2025-02-16T00:00:00.000Z",
      "status": "draft",
      "visibility": "public",
      "isPinned": false,
      "content": "\n## 简介\n\n示例\n\n## 如何使用\n\n示例",
      "locale": "zh"
    }
  ]
};
